# 服务器配置
[server]
listen_addr = "0.0.0.0:3001"
database_url = "mysql://user:pass@mysql:3306/bangumi"
assets_path = "/app/assets"

# 日志配置
[log]
level = "debug" # debug, info, warn, error

# 代理配置
[proxy]
enabled = false
http = "http://127.0.0.1:7890"
https = "http://127.0.0.1:7890"

# TMDB API 配置
[tmdb]
api_key = "your_tmdb_api_key"
base_url = "https://api.themoviedb.org/3"
image_base_url = "https://image.tmdb.org/t/p"
language = "zh-CN"

# Bangumi.tv API 配置
[bangumi_tv]
endpoint = "https://api.bgm.tv"
image_base_url = "https://lain.bgm.tv"

# Mikan 配置
[mikan]
endpoint = "https://mikanani.me"

# 下载器配置
# 115网盘下载器配置
[downloader.pan115]
enabled = false
cookies = "Your 115 cookies"
max_requests_per_second = 1
download_dir = "/animes"
# 下载完成后是否删除任务, 不会删除文件，只会删除任务
delete_task_on_completion = true
max_retry_count = 1
retry_min_interval = "30s"
retry_max_interval = "10m"
download_timeout = "2h"
priority = 10

# qbittorrent 下载器配置
[downloader.qbittorrent]
enabled = false
download_dir = "/animes"
username = "admin"
password = "adminadmin"
url = "http://127.0.0.1:8080"
max_retry_count = 1
retry_min_interval = "30s"
retry_max_interval = "10m"
download_timeout = "2h"
# 下载完成后是否删除任务, 不会删除文件，只会删除任务
delete_task_on_completion = false
priority = 10
# 可选，如果你需要在线播放qb下载的文件，请设置此选项，该目录指向qbittorrent的下载目录
mount_path = "/downloads"

[downloader.transmission]
enabled = false
url = "http://localhost:9091/transmission/rpc"
username = "admin"
password = "123456"
download_dir = "/downloads/complete"
# 可选，如果你需要在线播放qb下载的文件，请设置此选项，该目录指向qbittorrent的下载目录
mount_path = "/Users/lyqingye/Desktop/docker/ts-downloader/complete"
max_requests_per_second = 1
max_retry_count = 1
retry_min_interval = "30s"
retry_max_interval = "10m"
download_timeout = "2h"
delete_task_on_completion = false
priority = 0

# Telegram 通知配置
[notify.telegram]
enabled = false
token = "your_bot_token"
chat_id = "your_chat_id"

# 文件名解析器配置
# 三选一即可: siliconflow, deepseek, deepbricks

[parser.siliconflow]
enabled = false
api_key = "your_api_key"
base_url = "https://api.siliconflow.com"
model = "gpt-4"

[parser.deepseek]
enabled = false
api_key = "your_api_key"
base_url = "https://api.deepseek.com"
model = "deepseek-chat"

[parser.deepbricks]
enabled = false
api_key = "your_api_key"
base_url = "https://api.deepbricks.com"
model = "gpt-4"

# 原生解析器
[parser.raw]
enabled = true
