version: '3.8'

services:
  app:
    build: .
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      - DATABASE_URL=mysql://root:123456@mysql:3306/your_database_name

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: your_database_name
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./develop/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p123456"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  mysql_data: 