version: "3.8"

services:
  mysql:
    restart: unless-stopped
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: bangumi
    ports:
      - "3306:3306"
    volumes:
      - ./data:/var/lib/mysql
      - ./develop/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "localhost",
          "-u",
          "root",
          "-p123456",
        ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - bangumi-network

  backend:
    restart: unless-stopped
    image: ghcr.io/lyqingye/bangumi-rs/backend:latest
    ports:
      - "3001:3001"
    volumes:
      - ./assets:/app/assets
      - ./config.toml:/app/config.toml
      - ./animes:/animes
    command: ["/app/bangumi", "start"]
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - bangumi-network
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/health"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 5s

  frontend:
    restart: unless-stopped
    image: ghcr.io/lyqingye/bangumi-rs/frontend:latest
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - bangumi-network
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

  watchtower:
    restart: unless-stopped
    image: containrrr/watchtower:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 60 --cleanup --label-enable
    networks:
      - bangumi-network

networks:
  bangumi-network:
    driver: bridge

