version: "3.8"

services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: bangumi
    ports:
      - "3306:3306"
    volumes:
      - ./data:/var/lib/mysql
      - ./develop/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "localhost",
          "-u",
          "root",
          "-p123456",
        ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - bangumi-network

  backend:
    image: ghcr.io/lyqingye/bangumi-rs/backend:master
    volumes:
      - ./assets:/app/assets
      - ./config.toml:/app/config.toml
      - ./animes:/animes
    command: ["/app/bangumi", "start"]
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - bangumi-network

  frontend:
    image: ghcr.io/lyqingye/bangumi-rs/frontend:master
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - bangumi-network

networks:
  bangumi-network:
    driver: bridge

