//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use super::sea_orm_active_enums::State;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "episode_download_tasks")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub bangumi_id: i32,
    #[sea_orm(primary_key, auto_increment = false)]
    pub episode_number: i32,
    pub state: State,
    pub ref_torrent_info_hash: Option<String>,
    pub created_at: DateTime,
    pub updated_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
