//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

pub mod prelude;

pub mod bangumi;
pub mod dictionary;
pub mod episode_download_tasks;
pub mod episodes;
pub mod file_name_parse_record;
pub mod mikan_scraper_record;
pub mod sea_orm_active_enums;
pub mod subscriptions;
pub mod torrent_download_tasks;
pub mod torrents;
