//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "torrents")]
pub struct Model {
    pub bangumi_id: i32,
    pub title: String,
    pub size: i64,
    #[sea_orm(primary_key, auto_increment = false, unique)]
    pub info_hash: String,
    #[sea_orm(column_type = "Text")]
    pub magnet: String,
    #[sea_orm(column_type = "Binary(255)", nullable)]
    pub data: Option<Vec<u8>>,
    pub pub_date: DateTime,
    pub download_url: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
