name: Release

on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string
      draft:
        description: "是否创建草稿版本"
        required: false
        type: boolean
        default: false
      prerelease:
        description: "是否为预发布版本"
        required: false
        type: boolean
        default: false
    secrets:
      RELEASE_TOKEN:
        required: true

jobs:
  create-release:
    runs-on: ubuntu-latest
    outputs:
      release_id: ${{ steps.create_release.outputs.id }}
      upload_url: ${{ steps.create_release.outputs.upload_url }}

    steps:
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
        with:
          tag_name: ${{ inputs.version }}
          release_name: Release ${{ inputs.version }}
          body: |
            Release ${{ inputs.version }}

            Please see the [changelog](./CHANGELOG.md) for details.
          draft: ${{ inputs.draft }}
          prerelease: ${{ inputs.prerelease }}

  release-frontend:
    needs: create-release
    uses: ./.github/workflows/release-frontend.yml
    with:
      version: ${{ inputs.version }}
      upload_url: ${{ needs.create-release.outputs.upload_url }}
    secrets:
      RELEASE_TOKEN: ${{ secrets.RELEASE_TOKEN }}

  release-backend:
    needs: create-release
    strategy:
      fail-fast: false
      matrix:
        target:
          - { arch: linux-amd64, triple: x86_64-unknown-linux-gnu }
          - { arch: linux-arm64, triple: aarch64-unknown-linux-gnu }
          - { arch: macos-amd64, triple: x86_64-apple-darwin }
          - { arch: macos-arm64, triple: aarch64-apple-darwin }
    uses: ./.github/workflows/release-backend.yml
    with:
      version: ${{ inputs.version }}
      upload_url: ${{ needs.create-release.outputs.upload_url }}
      target: ${{ matrix.target.triple }}
      name: ${{ matrix.target.arch }}
    secrets:
      RELEASE_TOKEN: ${{ secrets.RELEASE_TOKEN }}

