/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    LogViewer: typeof import('./src/components/LogViewer.vue')['default']
    MediaCard: typeof import('./src/components/MediaCard.vue')['default']
    MessageProvider: typeof import('./src/components/MessageProvider.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SnackbarProvider: typeof import('./src/components/SnackbarProvider.vue')['default']
    SubscribeDialog: typeof import('./src/components/SubscribeDialog.vue')['default']
  }
}
